version: "2.0"

services:
  spacedeck:
    build: .
    container_name: spacedeck
    ports:
      - "9666:9666"
    volumes:
      - ./storage:/app/storage
      # - /Users/user/Desktop/github/spacedeck-open/storage/database.sqlite:/app/database.sqlite
    networks:
      - db-net
    depends_on:
      - db
  db:
    image: mysql:5.6.50
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: opendeck
    volumes:
     - ./storage/mysql:/var/lib/mysql
    networks:
      - db-net
networks:
  db-net:
